services:
  api:
    image: anestesia-tech.gitlab.yandexcloud.net:5050/ops/bookstore:latest
    restart: always
    environment:
      FLASK_APP: "app/__init__.py"
      DATABASE_URL: "${DB_URL}"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  db:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
      POSTGRES_DB: "${DB}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  proxy:
    build:
      context: ./nginx
    restart: always
    ports:
      - 8082:80
    depends_on:
      api:
        condition: service_healthy

volumes:
  pg_data:

